export const API_URL = 'http://localhost:5000/api' // Base URL pour toutes les API
export const TOKEN_KEY = 'auth_token' // Nom de la clé utilisée pour stocker le token dans le localStorage
export const TIMEOUT = 5000 // Timeout par défaut pour les requêtes HTTP

export const DataStructure = {
  produit: [
    {
      name: 'name',
      label: 'Nom du produit',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'brand',
      label: 'Marque',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'description',
      label: 'Description',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'price',
      label: 'Prix (€)',
      type: 'TextField',
      format: 'float',
      required: true,
    },
    {
      name: 'category',
      label: 'Catégorie',
      type: 'Select',
      required: true,
    },
    {
      name: 'stock',
      label: 'Stock',
      type: 'TextField',
      format: 'integer',
      required: true,
    },
    {
      name: 'image',
      label: 'Image',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'featured',
      label: 'Marquer comme produit à la une ?',
      type: 'CheckBox',
      required: false,
    },
  ],
  catégorie: [
    {
      name: 'name',
      label: 'Nom de la catégorie',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'description',
      label: 'Description',
      type: 'TextField',
      format: 'string',
      required: true,
    },
  ],
  utilisateur: [
    {
      name: 'firstname',
      label: 'Prénom',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'lastname',
      label: 'Nom',
      type: 'TextField',
      format: 'string',
      required: true,
    },
    {
      name: 'email',
      label: 'Adresse e-mail',
      type: 'TextField',
      format: 'email',
      required: true,
    },
    {
      name: 'gender',
      label: 'Sexe',
      type: 'TextField',
      format: 'string',
      required: false,
    },
    {
      name: 'birthdate',
      label: 'Date de naissance',
      type: 'TextField',
      format: 'date',
      required: false,
    },
    {
      name: 'verified',
      label: 'Compte vérifié ?',
      type: 'CheckBox',
      required: false,
    },
    {
      name: 'active',
      label: 'Compte actif ?',
      type: 'CheckBox',
      required: false,
    },
    {
      name: 'role',
      label: 'Rôle',
      type: 'Select',
      required: true,
    },
    // {
    //   name: 'password',
    //   label: 'Mot de passe',
    //   type: 'TextField',
    //   format: 'password',
    //   required: true,
    // },
    // {
    //   name: 'signup_date',
    //   label: "Date d'inscription",
    //   type: 'TextField',
    //   format: 'date',
    //   required: false,
    // },
    // {
    //   name: 'last_login_date',
    //   label: 'Dernière connexion',
    //   type: 'TextField',
    //   format: 'date',
    //   required: false,
    // },
    // {
    //   name: 'resetPasswordToken',
    //   label: 'Token de réinitialisation du mot de passe',
    //   type: 'TextField',
    //   format: 'string',
    //   required: false,
    // },
    // {
    //   name: 'resetPasswordExpires',
    //   label: 'Expiration du token de réinitialisation du mot de passe',
    //   type: 'TextField',
    //   format: 'date',
    //   required: false,
    // },
    // {
    //   name: 'settings',
    //   label: 'Paramètres',
    //   type: 'TextField',
    //   format: 'object',
    //   required: false,
    // },
    {
      name: 'newsletter_optin',
      label: 'Opt-in newsletter',
      type: 'CheckBox',
      required: false,
    },
  ],
}

export const DefaultData = {
  produit: {
    name: '',
    brand: '',
    description: '',
    price: '',
    category: '',
    stock: '',
    featured: false,
    image: '',
  },
  catégorie: {
    name: '',
    description: '',
  },
  utilisateur: {
    firstname: '',
    lastname: '',
    email: '',
    gender: '',
    birthdate: '',
    role: 'user',
    verified: false,
    active: true,
  },
}
